project_name: teldrive-upload
env:
  - GO111MODULE=on
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{ .ModulePath }}/pkg/consts.Version={{ .Version }}
      - -X {{ .ModulePath }}/pkg/consts.Commit={{ .ShortCommit }}
      - -X {{ .ModulePath }}/pkg/consts.CommitDate={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
